
apiVersion: v1
kind: Service
metadata:
  name: flask-file-manager
spec:
  selector:
    app: flask-file-manager
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

